name: Update Dependencies

on:
  schedule:
    # Run weekly on Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install uv
      run: |
        pip install uv
    
    - name: Update dependencies
      run: |
        # Create a virtual environment with explicit path
        uv venv .venv
        
        # Use uv directly with --python pointing to the venv
        VENV_PYTHON="$(pwd)/.venv/bin/python"
        
        # Install current dependencies
        uv pip install --python $VENV_PYTHON -e ".[dev]"
        
        # Check for updates and apply them
        uv pip compile --python $VENV_PYTHON pyproject.toml --upgrade
        
        # Generate updated requirements.txt
        uv pip freeze --python $VENV_PYTHON > requirements.txt
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "chore: update dependencies"
        body: |
          This PR updates project dependencies to their latest versions.
          
          Updated using `uv pip compile --upgrade`.
          
          Auto-generated by the Update Dependencies workflow.
        branch: dependencies-update
        base: dev  # Target the dev branch
        labels: dependencies