name: "Dependabot Updates"

on:
  schedule:
    - cron: "0 0 * * 0" # Runs weekly at midnight UTC on Sundays

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify Dependabot PR
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: echo "PR is not from Dependabot, skipping."

      - name: Fetch Dependabot metadata
        uses: dependabot/fetch-metadata@v1
        with:
          alert-lookup: true
          compat-lookup: true
          github-token: "${{ secrets.GITHUB_TOKEN }}"
