name: Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        pip install black ruff
    
    - name: Format with black
      run: |
        # Format the code instead of just checking
        black .
        # Check if any changes were made and commit them
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git diff --staged --quiet || git commit -m "Apply automatic formatting with Black"
    
    - name: Lint with ruff
      run: |
        # Fix issues automatically
        ruff check --fix .
        # Check if any changes were made and commit them
        git add .
        git diff --staged --quiet || git commit -m "Apply automatic fixes with Ruff"

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
      with:
        # Fetch all history for all branches and tags
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install pytest pytest-cov
        pip install -e ".[dev]"
    
    - name: Run tests
      run: |
        pytest -v

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install build dependencies
      run: |
        pip install build twine
    
    - name: Build package
      run: |
        python -m build
    
    - name: Check package
      run: |
        twine check dist/*