name: Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install uv
      run: |
        pip install uv
    
    - name: Install dependencies
      run: |
        # Install directly with --system flag to avoid venv issues
        uv pip install --system -e ".[dev]"
    
    - name: Lint with ruff
      run: |
        uv pip install --system ruff
        ruff check .
    
    - name: Check formatting with black
      run: |
        uv pip install --system black
        black --check .
    
    - name: Test with pytest
      run: |
        uv pip install --system pytest pytest-cov
        pytest --cov=scaffold_fastapi tests/
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false